name: format

on:
  - push
  - pull_request

jobs:
  dartfmt:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run format
        run: dart format --set-exit-if-changed .

  import_sorter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Run import_sorter
        run: |
          pub get
          pub run import_sorter:main --exit-if-changed
