name: test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: dart:stable

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pub get
      - name: Run tests
        run: pub run test
